# 1-🐼 Pandas Mastery — Lesson 1: DataFrames & Selection
🔹 1. What is a DataFrame?
A DataFrame is a table with rows and columns — like an Excel sheet but programmable.

In [3]:
import pandas as pd
# creating dataframe
df = pd.DataFrame({
    'name':['brayn', 'khan', 'ali', 'shoaib', 'john'],
    'runs':[ 22, 55, 67, 78, 65],
    'strike_rate':[ 80, 100, 20, 59, 45]
    
})
df.head(3)

    name  runs  strike_rate
0  brayn    22           80
1   khan    55          100
2    ali    67           20

# 2- Column Selection

In [4]:
# Use the same DataFrame you created earlier.

# Exercise 2.1
# Select only the name column.

df['name']

0     brayn
1      khan
2       ali
3    shoaib
4      john
Name: name, dtype: str

In [5]:
#Exercise 2.2
# Select name and strike_rate together.

df[['name','strike_rate']]

     name  strike_rate
0   brayn           80
1    khan          100
2     ali           20
3  shoaib           59
4    john           45

In [6]:
df.loc[:, ['runs', 'strike_rate']]

   runs  strike_rate
0    22           80
1    55          100
2    67           20
3    78           59
4    65           45

In [7]:
df

     name  runs  strike_rate
0   brayn    22           80
1    khan    55          100
2     ali    67           20
3  shoaib    78           59
4    john    65           45

In [8]:
df.iloc[:, [0,2]]
df.iloc[-1:]

   name  runs  strike_rate
4  john    65           45

In [9]:
df_small = df[['name', 'runs']]
df_small

     name  runs
0   brayn    22
1    khan    55
2     ali    67
3  shoaib    78
4    john    65

In [10]:
#Exercise 3.1
# Filter players with runs > 50.
df[(df['runs']> 50)]

     name  runs  strike_rate
1    khan    55          100
2     ali    67           20
3  shoaib    78           59
4    john    65           45

In [11]:
# # Exercise 3.2
# Filter players with:runs > 50
# strike_rate > 80
# (Use AND)

# df[(df['strike_rate'] > 80) & (df['runs'] > 50)]

df[(df['strike_rate'] > 80) | (df['runs'] > 50)]

     name  runs  strike_rate
1    khan    55          100
2     ali    67           20
3  shoaib    78           59
4    john    65           45