In [ ]:
#importing libraries
import numpy as np
import pandas as pd

In [ ]:
# # Basic data structures in pandas
# Pandas provides two types of classes for handling data:
# Series: a one-dimensional labeled array holding data of any type
# such as integers, strings, Python objects etc
# DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

In [ ]:
# object creation: Creating series by passing a list of values, letting pandas create a default rangeindex.
import numpy as np
import pandas as pd
s= pd.Series([1, 3, 5, np.nan, 6, 8])
s

In [ ]:
# creating dataframe by passing a NumPy array with'datetime index'using
# date_range() funtion and labeled column
dates = pd.date_range('20130101', periods = 6)
dates

df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = list('ABCD'))
df

In [ ]:
#Creating a DataFrame by passing a dictionary of objects where the keys are column labels and the values are the column values
import pandas as pd
import numpy as np
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

In [ ]:
# what is series , what is data frame and how to create them
import pandas as pd
s = pd.Series([10, 20, 30, 40])
s

In [ ]:
#create a series of 5 numbers of your choice
s = pd.Series([1, 4, 5, 6, 7])
s

In [1]:
#creating data frame
import pandas as pd

df3 = pd.DataFrame(
    {
        'Product': ['apple', 'banana', 'mango'],
        'Price': [2.5, 1.3, 4],
        'Quantity': [10, 5, 7]
    }
)
df3

  Product  Price  Quantity
0   apple    2.5        10
1  banana    1.3         5
2   mango    4.0         7

In [2]:
# Viewing data: using dataframe from previous example
import pandas as pd

df3 = pd.DataFrame(
    {
        'Product': ['apple', 'banana', 'mango'],
        'Price': [2.5, 1.3, 4],
        'Quantity': [10, 5, 7]
    }
)
df3.head(2)

  Product  Price  Quantity
0   apple    2.5        10
1  banana    1.3         5

In [3]:
df3.tail(2)

  Product  Price  Quantity
1  banana    1.3         5
2   mango    4.0         7

In [4]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   3 non-null      object
 1   Price     3 non-null      float64
 2   Quantity  3 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes

In [5]:
df3.describe()

          Price   Quantity
count  3.000000   3.000000
mean   2.600000   7.333333
std    1.352775   2.516611
min    1.300000   5.000000
25%    1.900000   6.000000
50%    2.500000   7.000000
75%    3.250000   8.500000
max    4.000000  10.000000

In [21]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6 ,7 ,8]
})
df
df['A']
# df.loc[2]
# df.loc[1, 'B']

0    1
1    2
2    3
3    4
Name: A, dtype: int64

In [1]:
import pandas as pd
df = pd.DataFrame({
    'Age': [12, 25, 30, 17, 48]
})
df

   Age
0   12
1   25
2   30
3   17
4   48

In [2]:
df[df['Age'] > 18]

   Age
1   25
2   30
4   48

In [13]:
import pandas as pd
df = pd.DataFrame({
    'Age': [12, 25, 30, 17, 48]
})
df

   Age
0   12
1   25
2   30
3   17
4   48

In [15]:
df[(df['Age'] >= 20) & (df['Age'] <= 35)]

   Age
1   25
2   30